server:
  port: 8081
spring:
  application:
    name: demomicro
  cloud:
    kubernetes:
      reload:
        enabled: true
        monitoring-config-maps: true
        strategy: refresh
        mode: event
      config:
        enabled: true
        name: dbcrudmicro
db:
  couchbase:
    username: ${CB_USERNAME}
    password: ${CB_PASSWORD}