server:
  port: 8081
spring:
  application:
    name: dbcrudmicro
  cloud:
    kubernetes:
      reload:
        enabled: true
      config:
        enabled: true
db:
  couchbase:
    username: ${CB_USERNAME}
    password: ${CB_PASSWORD}